//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoPilot.Speedway.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoPilot.Speedway.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for connection ....
        /// </summary>
        public static string AllowOnCelluralAndBatery {
            get {
                return ResourceManager.GetString("AllowOnCelluralAndBatery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for Wi-Fi network ....
        /// </summary>
        public static string AllowOnWifiAndBatery {
            get {
                return ResourceManager.GetString("AllowOnWifiAndBatery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin external power and Wi-Fi ....
        /// </summary>
        public static string AllowOnWifiAndExternalPower {
            get {
                return ResourceManager.GetString("AllowOnWifiAndExternalPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close an applicationpress the back button again. The recording will be terminated..
        /// </summary>
        public static string AppEndDescription {
            get {
                return ResourceManager.GetString("AppEndDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit application?.
        /// </summary>
        public static string AppEndTitle {
            get {
                return ResourceManager.GetString("AppEndTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avarage speed: .
        /// </summary>
        public static string AvarageSpeed {
            get {
                return ResourceManager.GetString("AvarageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your are not sign in.
        /// </summary>
        public static string Backup_NotSignedIn {
            get {
                return ResourceManager.GetString("Backup_NotSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged into any cloud storage service. For proper operation of backups you need to login..
        /// </summary>
        public static string Backup_NotSignedIn_Description {
            get {
                return ResourceManager.GetString("Backup_NotSignedIn_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow backup on start.
        /// </summary>
        public static string BackupAllowOnStart {
            get {
                return ResourceManager.GetString("BackupAllowOnStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really wan to load backup from cloud storage? This action is not reversable!.
        /// </summary>
        public static string BackupApplyDescription {
            get {
                return ResourceManager.GetString("BackupApplyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load backup?.
        /// </summary>
        public static string BackupApplyTitle {
            get {
                return ResourceManager.GetString("BackupApplyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current backup id.
        /// </summary>
        public static string BackupCurrentId {
            get {
                return ResourceManager.GetString("BackupCurrentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download into device.
        /// </summary>
        public static string BackupDownload {
            get {
                return ResourceManager.GetString("BackupDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup main data.
        /// </summary>
        public static string BackupMainFile {
            get {
                return ResourceManager.GetString("BackupMainFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup file not found on server..
        /// </summary>
        public static string BackupNotFoundDescription {
            get {
                return ResourceManager.GetString("BackupNotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup not found.
        /// </summary>
        public static string BackupNotFoundTitle {
            get {
                return ResourceManager.GetString("BackupNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup options.
        /// </summary>
        public static string BackupOptions {
            get {
                return ResourceManager.GetString("BackupOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no backup.
        /// </summary>
        public static string BackupUnknown {
            get {
                return ResourceManager.GetString("BackupUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read articles on blog.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obd is not allowed to use.
        /// </summary>
        public static string BluetoothIsNotAllowed {
            get {
                return ResourceManager.GetString("BluetoothIsNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current lap.
        /// </summary>
        public static string CurrentLap {
            get {
                return ResourceManager.GetString("CurrentLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device not found, tap to refresh.
        /// </summary>
        public static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance unit.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download backup.
        /// </summary>
        public static string DownloadBackup {
            get {
                return ResourceManager.GetString("DownloadBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download bacup from your storage.
        /// </summary>
        public static string DownloadBackupHelp {
            get {
                return ResourceManager.GetString("DownloadBackupHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but the application has encountered an unexpected error. Please help me improve the application and send me an email with an error message after next start. The application will be closed now..
        /// </summary>
        public static string ErrorDescription {
            get {
                return ResourceManager.GetString("ErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And it&apos;s down :(.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fastest lap: .
        /// </summary>
        public static string FastestsLap {
            get {
                return ResourceManager.GetString("FastestsLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liters.
        /// </summary>
        public static string FueledUnit {
            get {
                return ResourceManager.GetString("FueledUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallon.
        /// </summary>
        public static string Gallon {
            get {
                return ResourceManager.GetString("Gallon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for quality signal from the GPS receiver. Without this, it is not possible to start measuring of circuit..
        /// </summary>
        public static string GpsNotAccurred {
            get {
                return ResourceManager.GetString("GpsNotAccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poor quality signal.
        /// </summary>
        public static string GpsNotAccurredTitle {
            get {
                return ResourceManager.GetString("GpsNotAccurredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous laps.
        /// </summary>
        public static string Laps {
            get {
                return ResourceManager.GetString("Laps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap times.
        /// </summary>
        public static string LapsTime {
            get {
                return ResourceManager.GetString("LapsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last backup.
        /// </summary>
        public static string LastBackup {
            get {
                return ResourceManager.GetString("LastBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More obd devices, tap to select one.
        /// </summary>
        public static string MoreDevices {
            get {
                return ResourceManager.GetString("MoreDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lap name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not finished any round. It is not possible to attempt to save this record. Get off at least one first round and then stop recording..
        /// </summary>
        public static string NoLap_Description {
            get {
                return ResourceManager.GetString("NoLap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not completed round.
        /// </summary>
        public static string NoLap_Title {
            get {
                return ResourceManager.GetString("NoLap_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is OBD and where it buy?.
        /// </summary>
        public static string ObdBuy {
            get {
                return ResourceManager.GetString("ObdBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-board diagnostics (OBD) is an automotive term referring to a vehicle&apos;s self-diagnostic and reporting capability. OBD systems give the vehicle owner or repair technician access to the status of the various vehicle sub-systems. The amount of diagnostic information available via OBD has varied widely since its introduction in the early 1980s&apos; versions of on-board vehicle computers. Early versions of OBD would simply illuminate a malfunction indicator light or &quot;idiot light&quot; if a problem was detected but woul [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ObdDescription {
            get {
                return ResourceManager.GetString("ObdDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something terrible has happened.
        /// </summary>
        public static string ObdFatalError {
            get {
                return ResourceManager.GetString("ObdFatalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about OBD module.
        /// </summary>
        public static string ObdInfo {
            get {
                return ResourceManager.GetString("ObdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ObdInfo_Title1 {
            get {
                return ResourceManager.GetString("ObdInfo_Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string ObdInfo_Title2 {
            get {
                return ResourceManager.GetString("ObdInfo_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to buy?.
        /// </summary>
        public static string ObdInfo_Title3 {
            get {
                return ResourceManager.GetString("ObdInfo_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup data.
        /// </summary>
        public static string OpenBackup {
            get {
                return ResourceManager.GetString("OpenBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open backup in browser.
        /// </summary>
        public static string OpenLinkInBrowser {
            get {
                return ResourceManager.GetString("OpenLinkInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device out of range, tap to refresh.
        /// </summary>
        public static string OutOfRangeOfDevice {
            get {
                return ResourceManager.GetString("OutOfRangeOfDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to / h.
        /// </summary>
        public static string PerHour {
            get {
                return ResourceManager.GetString("PerHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate and review.
        /// </summary>
        public static string RateApp {
            get {
                return ResourceManager.GetString("RateApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving data from device.
        /// </summary>
        public static string ReceivingDataFromObd {
            get {
                return ResourceManager.GetString("ReceivingDataFromObd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last termination of application caused by error. Want to help me improve an application and report a bug?.
        /// </summary>
        public static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application crash report.
        /// </summary>
        public static string ReportTitle {
            get {
                return ResourceManager.GetString("ReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching ....
        /// </summary>
        public static string Searching {
            get {
                return ResourceManager.GetString("Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select OBD device.
        /// </summary>
        public static string SelectObdDevice {
            get {
                return ResourceManager.GetString("SelectObdDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send backup link by email.
        /// </summary>
        public static string SendByEmail {
            get {
                return ResourceManager.GetString("SendByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is link for download your backuped data.{E}Your backup id is {0}{E}Click on {1} to start download..
        /// </summary>
        public static string SendByEmailBody {
            get {
                return ResourceManager.GetString("SendByEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link on your backup.
        /// </summary>
        public static string SendByEmailSubject {
            get {
                return ResourceManager.GetString("SendByEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share circuit.
        /// </summary>
        public static string ShareCircuit {
            get {
                return ResourceManager.GetString("ShareCircuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share now!.
        /// </summary>
        public static string ShareLap {
            get {
                return ResourceManager.GetString("ShareLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social.
        /// </summary>
        public static string Social {
            get {
                return ResourceManager.GetString("Social", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the car, start the measurement is possible only if you stand on the spot. Your current speed is:.
        /// </summary>
        public static string SpeedDescription {
            get {
                return ResourceManager.GetString("SpeedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop your car.
        /// </summary>
        public static string SpeedTitle {
            get {
                return ResourceManager.GetString("SpeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application now waiting for the launch. When you move, application is automatically starts to count time. You can cancel action now or anytime during the ride..
        /// </summary>
        public static string StartDescription {
            get {
                return ResourceManager.GetString("StartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start racing.
        /// </summary>
        public static string StartRacing {
            get {
                return ResourceManager.GetString("StartRacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start up when you&apos;re ready!.
        /// </summary>
        public static string StartTitle {
            get {
                return ResourceManager.GetString("StartTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to laps.
        /// </summary>
        public static string TotalLaps {
            get {
                return ResourceManager.GetString("TotalLaps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on your bluetooth by tap here.
        /// </summary>
        public static string TurnOnBluetooth {
            get {
                return ResourceManager.GetString("TurnOnBluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup page.
        /// </summary>
        public static string Tutorial_Backup {
            get {
                return ResourceManager.GetString("Tutorial_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After clicking on the &quot;Backup&quot; in the settings page, you will see information about the backup. Here you will find the date of the last backup, the backup identifier and settings. 1) Whether you want to do a backup after starting the application and 2) when you want to backup your data, you must login into cloud storage..
        /// </summary>
        public static string Tutorial_Backup_Description {
            get {
                return ResourceManager.GetString("Tutorial_Backup_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup main file menu.
        /// </summary>
        public static string Tutorial_BackupFileMenu {
            get {
                return ResourceManager.GetString("Tutorial_BackupFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are four important buttons in the menu. 1) Use this button to back up the main file 2) If the backup is created, you can refer to it in the browser (and store) or 3) let it send the email. If you have a backup on cloud storage 4) you can download it by click on this button..
        /// </summary>
        public static string Tutorial_BackupFileMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_BackupFileMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close tutorial?.
        /// </summary>
        public static string Tutorial_End {
            get {
                return ResourceManager.GetString("Tutorial_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can i have close the tutorial? You can rerun this tutorial from more menu..
        /// </summary>
        public static string Tutorial_End_Description {
            get {
                return ResourceManager.GetString("Tutorial_End_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please take a few minutes to this tutorial..
        /// </summary>
        public static string Tutorial_Information {
            get {
                return ResourceManager.GetString("Tutorial_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circuits menu.
        /// </summary>
        public static string Tutorial_LapsMenu {
            get {
                return ResourceManager.GetString("Tutorial_LapsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a list of all circuits 1). There are only unique to each round and is shown best time. Names of circuits are generated automatically by the length and location. The program automatically detects the same circuits, so you can try to ride over and over again..
        /// </summary>
        public static string Tutorial_LapsMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_LapsMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main screen.
        /// </summary>
        public static string Tutorial_MainScreen {
            get {
                return ResourceManager.GetString("Tutorial_MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On the main screen you can see a map of your current location, where you are. Here you will find information about the status of GPS signal and if you move, you will see information about your speed. Start button can be used only if the car is not moving and the GPS signal quality is good..
        /// </summary>
        public static string Tutorial_MainScreen_Description_One {
            get {
                return ResourceManager.GetString("Tutorial_MainScreen_Description_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main menu contains four main buttons. 1) Times, 2) Laps, 3) Share and 4) Settings and others..
        /// </summary>
        public static string Tutorial_MainScreen_Description_Two {
            get {
                return ResourceManager.GetString("Tutorial_MainScreen_Description_Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle measurement.
        /// </summary>
        public static string Tutorial_Measurement {
            get {
                return ResourceManager.GetString("Tutorial_Measurement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After pressing the start button, the application will wait for a car move. Once set in motion, it automatically starts measuring and displaying the track. The application is currently inactive and the only option is stop measurement by pressing stop button. If you do not do even one lap, time is not counted..
        /// </summary>
        public static string Tutorial_Measurement_Description {
            get {
                return ResourceManager.GetString("Tutorial_Measurement_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting menu.
        /// </summary>
        public static string Tutorial_MoreMenu {
            get {
                return ResourceManager.GetString("Tutorial_MoreMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you click on the other menu (three dots), there appears a list of other settings in front of you. 1) Used to enable GPS, 2) Connect the OBD module if there are more, you can select one, 3) Is used for uploading or sending backup. In this menu are also buttons to set the units, links to social networks and more..
        /// </summary>
        public static string Tutorial_MoreMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_MoreMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And that&apos;s all.
        /// </summary>
        public static string Tutorial_ThanksEnd {
            get {
                return ResourceManager.GetString("Tutorial_ThanksEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tutorial is over and you can always run the tutorial again from application menu..
        /// </summary>
        public static string Tutorial_ThanksEnd_Description {
            get {
                return ResourceManager.GetString("Tutorial_ThanksEnd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for installing CoPilot SpeedWay..
        /// </summary>
        public static string Tutorial_ThankYou {
            get {
                return ResourceManager.GetString("Tutorial_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times menu.
        /// </summary>
        public static string Tutorial_TimesMenu {
            get {
                return ResourceManager.GetString("Tutorial_TimesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this menu is situated, like on the home screen, 1) start button. After a successful lap record there will be displayed all records 2) with number of round, the best time and average speed..
        /// </summary>
        public static string Tutorial_TimesMenu_Description {
            get {
                return ResourceManager.GetString("Tutorial_TimesMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: This application is used to measure the speed on the rail for this purpose. Do not use this application in the normal traffic!.
        /// </summary>
        public static string Tutorial_Warning {
            get {
                return ResourceManager.GetString("Tutorial_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        public static string Tutorial_Welcome {
            get {
                return ResourceManager.GetString("Tutorial_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What is CoPilot SpeedWay?.
        /// </summary>
        public static string Tutorial_WhatIsIt {
            get {
                return ResourceManager.GetString("Tutorial_WhatIsIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CoPilot Speedway is an application that is used to measure the time circuits and displaying statistics. Applications can detect the same rounds, automatically check if you cross start and record the fastest times. And do not even have to start from the same place. The application also cooperates with CoPilot..
        /// </summary>
        public static string Tutorial_WhatIsIt_Description {
            get {
                return ResourceManager.GetString("Tutorial_WhatIsIt_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used accounts on backup.
        /// </summary>
        public static string UsedAccounts {
            get {
                return ResourceManager.GetString("UsedAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use gps senzor.
        /// </summary>
        public static string UseGpsSenzor {
            get {
                return ResourceManager.GetString("UseGpsSenzor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use obd device.
        /// </summary>
        public static string UseObdDevice {
            get {
                return ResourceManager.GetString("UseObdDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have moved away from the original path. The recording was automatically ended and this round has not been counted..
        /// </summary>
        public static string WrongLap_Description {
            get {
                return ResourceManager.GetString("WrongLap_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path.
        /// </summary>
        public static string WrongLap_Title {
            get {
                return ResourceManager.GetString("WrongLap_Title", resourceCulture);
            }
        }
    }
}
